version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "00 12 1 * *"
    labels:
      - "Type: Dependencies :arrow_up:"
    groups:
      github-actions:
        patterns:
          - "*"
