name: Bug report
description: Report an error or unexpected behaviour
labels:
  - "Type: Bug :bug:"

body:
  - type: markdown
    attributes:
      value: |
        Welcome!

  - type: checkboxes
    attributes:
      label: "I Have checked the following"
      options:
        - label: I have searched the issue tracker for similar issues
          required: true
        - label: I have the latest version of [Quarto CLI](https://github.com/quarto-dev/quarto-cli/releases/latest)
          required: true
        - label: I have the latest version of the Quarto extension
          required: true

  - type: textarea
    attributes:
      label: Bug description
      description: Description of the bug.
      placeholder: Please describe the bug here.

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: |
        Tell us how to reproduce this bug.

  - type: textarea
    attributes:
      label: Actual behaviour
      description: Tell us what happens instead.

  - type: textarea
    attributes:
      label: Expected behaviour
      description: Tell us what should happen.

  - type: textarea
    attributes:
      label: Your environment
      description: |
        Please document the IDE (_e.g._ RStudio, Positron, VSCode, NVim), its version, and the operating system you're running (_e.g., MacOS Ventura 13.4, Windows 11, Linux Debian 11, _etc._).
      placeholder: |
        - IDE: RStudio 2023.03.1+446 | VSCode | Positron
        - OS: MacOS Ventura 13.4 | Windows | Ubuntu

  - type: markdown
    attributes:
      value: "_Thanks for submitting this bug report!_"
